-- MySQL Script generated by MySQL Workbench
-- ned 03 apr 2022 00:42:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entry` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(45) NULL,
  `price` TINYINT(1) NULL,
  `accessibility` VARCHAR(45) NULL,
  `season` VARCHAR(45) NULL,
  `accomodation` TINYINT NULL,
  `Region_idRegion` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `image` VARCHAR(100) NULL,
  PRIMARY KEY (`id`, `Region_idRegion`),
  INDEX `fk_Entry_Region1_idx` (`Region_idRegion` ASC) VISIBLE,
  CONSTRAINT `fk_Entry_Region1`
    FOREIGN KEY (`Region_idRegion`)
    REFERENCES `mydb`.`region` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entryHasCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entryHasCategory` (
  `idEntry` INT NOT NULL AUTO_INCREMENT,
  `idCategory` INT NOT NULL,
  PRIMARY KEY (`idEntry`, `idCategory`),
  INDEX `fk_Entry_has_Category_Category1_idx` (`idCategory` ASC) VISIBLE,
  INDEX `fk_Entry_has_Category_Entry_idx` (`idEntry` ASC) VISIBLE,
  CONSTRAINT `fk_Entry_has_Category_Entry`
    FOREIGN KEY (`idEntry`)
    REFERENCES `mydb`.`entry` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entry_has_Category_Category1`
    FOREIGN KEY (`idCategory`)
    REFERENCES `mydb`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`municipality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`municipality` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `Region_idRegion` INT NOT NULL,
  PRIMARY KEY (`id`, `Region_idRegion`),
  INDEX `fk_Municipality_Region1_idx` (`Region_idRegion` ASC) VISIBLE,
  CONSTRAINT `fk_Municipality_Region1`
    FOREIGN KEY (`Region_idRegion`)
    REFERENCES `mydb`.`region` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
